import { Html, Head, Main, NextScript } from 'next/document'

import { ColorModeScript } from '@chakra-ui/react'

import theme from '../../theme'
import Script from 'next/script'

export default function Document() {
  return (
    <Html>
      <Head>
        <title>Melon Vanilla Sour</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <Main />
        <NextScript />
        {/* Remove overscrolling behavior for Safari */}
        <Script strategy="afterInteractive">
          {`document.addEventListener('touchmove', function(event){
              event.preventDefault();
            }, { passive: false });
          `}
        </Script>
      </body>
    </Html>
  )
}
