import { Heading } from '@chakra-ui/react'
import { buildClient } from '../lib/contentful'
import Link from 'next/link'

import { Center, SimpleGrid } from '@chakra-ui/react'

import Base from '../../components/base'
import Head from 'next/head'
import PostThumbnail from '../../components/postThumbnail'

const client = buildClient()

export const getStaticProps = async () => {
  const { items } = await client.getEntries({
    content_type: 'post',
    order: '-sys.createdAt',
  })
  return {
    props: { posts: items },
  }
}

function Blog({ posts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Base>
        <SimpleGrid columns={[1, 1, 2]} spacing={4} w="full">
          {posts && posts.map((post) => <PostThumbnail post={post}></PostThumbnail>)}
        </SimpleGrid>
      </Base>
    </>
  )
}

export default Blog
