import { Heading } from '@chakra-ui/react'
import { buildClient } from '../lib/contentful'
import Link from 'next/link'

import { Center } from '@chakra-ui/react'

const client = buildClient()

export const getStaticProps = async () => {
  const { items } = await client.getEntries({
    content_type: 'post',
    order: '-sys.createdAt',
  })
  return {
    props: { posts: items },
  }
}

function HomePage({ posts }) {
  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Center>
        <main>
          <Heading>Melon Vanilla Sour</Heading>
          <div>
            <ul>
              {posts &&
                posts.map((post) => (
                  <li key={post.sys.id}>
                    <Link href={`/${post.fields.slug}`}>
                      <a>
                        <h2>{post.fields.title}</h2>
                      </a>
                    </Link>
                  </li>
                ))}
            </ul>
          </div>
        </main>
      </Center>
    </div>
  )
}

export default HomePage
