import { Box, Heading } from '@chakra-ui/react'
import { buildClient } from '../lib/contentful'
import Link from 'next/link'

import { Center, SimpleGrid, Text } from '@chakra-ui/react'

import Base from '../../components/base'
import Head from 'next/head'
import PostThumbnail from '../../components/postThumbnail'

const client = buildClient()

export const getStaticProps = async () => {
  const { items } = await client.getEntries({
    content_type: 'post',
    order: '-sys.createdAt',
  })
  return {
    props: { posts: items },
  }
}

function HomePage({ posts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Base>
        <Box mt={15}>
          <Center>
            <Text>Web Developer</Text>
          </Center>
          <SimpleGrid mt={25} columns={4} spacing={8}>
            <img width="100px" src="icons/javascript.svg" alt="javascript-icon" />
            <img width="100px" src="icons/nextdotjs.svg" alt="javascript-icon" />
            <img width="100px" src="icons/react.svg" alt="javascript-icon" />
          </SimpleGrid>
        </Box>
      </Base>
    </>
  )
}

export default HomePage
