import { Box, Heading } from '@chakra-ui/react'
import { buildClient } from '../lib/contentful'
import Link from 'next/link'

import { Center, SimpleGrid, Text, Image } from '@chakra-ui/react'

import Base from '../../components/base'
import Head from 'next/head'
import PostThumbnail from '../../components/postThumbnail'

const client = buildClient()

export const getStaticProps = async () => {
  const { items } = await client.getEntries({
    content_type: 'post',
    order: '-sys.createdAt',
  })
  return {
    props: { posts: items },
  }
}

function HomePage({ posts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Base>
        <Box>
          <Heading mb="40px">About Me</Heading>
          <Text>Web Developer</Text>
          <br />

          <Text>Contact: melonvanillasour@gmail.com</Text>
          <br />
          <Text>I'm pretty good with these things</Text>

          <SimpleGrid mt={25} columns={4} spacing={8}>
            <Image
              width="100px"
              src="icons/javascript.svg"
              alt="javascript-icon"
              _hover={{ transform: 'translate(0px, -10px)' }}
              transition="all 0.1s ease-out"
            />
            <a href="https://nextjs.org/" target="_blank">
              <img width="100px" src="icons/nextdotjs.svg" alt="javascript-icon" />
            </a>
            <img width="100px" src="icons/react.svg" alt="javascript-icon" />
            <img width="100px" src="icons/chakraui.svg" alt="javascript-icon" />
            <a href="https://nodejs.org/en/" target="_blank">
              <img width="100px" src="icons/nodedotjs.svg" alt="javascript-icon" />
            </a>
          </SimpleGrid>

          <Text>I'm ok with these things</Text>
          <SimpleGrid mt={25} columns={4} spacing={8}>
            <img width="100px" src="icons/ruby.svg" alt="javascript-icon" />
            <img width="100px" src="icons/php.svg" alt="javascript-icon" />
          </SimpleGrid>
        </Box>
      </Base>
    </>
  )
}

export default HomePage
