import { Heading } from '@chakra-ui/react'
import { buildClient } from '../lib/contentful'
import Link from 'next/link'

import { Center, SimpleGrid } from '@chakra-ui/react'

import Base from '../../components/base'
import Head from 'next/head'

function Projects() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Base>Coming Soon...</Base>
    </>
  )
}

export default Projects
